create table if not exists public.pilot_sessions (
  id uuid primary key,
  student_code text not null check (student_code ~ '^[A-Za-z0-9_-]{1,24}$'),
  grade integer not null check (grade between 8 and 10),
  created_at timestamptz not null default now()
);

create table if not exists public.pilot_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.pilot_sessions(id) on delete cascade,
  event_type text not null check (
    event_type in (
      'lesson_started',
      'step_completed',
      'quiz_answered',
      'quiz_completed',
      'next_lesson_clicked'
    )
  ),
  lesson_id text not null,
  step_index integer check (step_index is null or step_index >= 0),
  question_index integer check (question_index is null or question_index >= 0),
  selected_index integer check (selected_index is null or selected_index >= 0),
  is_correct boolean,
  is_misconception_check boolean,
  main_score integer check (main_score is null or main_score >= 0),
  main_question_count integer check (main_question_count is null or main_question_count >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.pilot_quiz_attempts (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.pilot_sessions(id) on delete cascade,
  lesson_id text not null,
  question_index integer not null check (question_index >= 0),
  selected_index integer not null check (selected_index >= 0),
  is_correct boolean not null,
  is_misconception_check boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists pilot_events_session_created_idx
  on public.pilot_events(session_id, created_at);

create index if not exists pilot_events_type_lesson_idx
  on public.pilot_events(event_type, lesson_id);

create index if not exists pilot_quiz_attempts_session_question_idx
  on public.pilot_quiz_attempts(session_id, lesson_id, question_index, created_at);

alter table public.pilot_sessions enable row level security;
alter table public.pilot_events enable row level security;
alter table public.pilot_quiz_attempts enable row level security;

drop policy if exists "pilot sessions insert only" on public.pilot_sessions;
drop policy if exists "pilot events insert only" on public.pilot_events;
drop policy if exists "pilot quiz attempts insert only" on public.pilot_quiz_attempts;

create policy "pilot sessions insert only"
  on public.pilot_sessions
  for insert
  to anon, authenticated
  with check (true);

create policy "pilot events insert only"
  on public.pilot_events
  for insert
  to anon, authenticated
  with check (true);

create policy "pilot quiz attempts insert only"
  on public.pilot_quiz_attempts
  for insert
  to anon, authenticated
  with check (true);

comment on table public.pilot_sessions is
  'Anonymous pilot sessions. student_code must be a non-PII classroom code such as S01.';

comment on table public.pilot_events is
  'Insert-only pilot telemetry for MVP validation.';

comment on table public.pilot_quiz_attempts is
  'Insert-only quiz attempts for aggregate MVP validation reports.';
